<a href="https://colab.research.google.com/github/12Sowmyap/Books-Python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
sample_matrix=np.array([list_of_lists])
sample_matrix

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(2,50,4)

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46])

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.zeros(6,int)

array([0, 0, 0, 0, 0, 0])

In [ ]:
np.zeros(9,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(2,20,4)

array([ 2.,  8., 14., 20.])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(5,6)

array([[0.08088548, 0.18427712, 0.63456254, 0.61203678, 0.09767026,
        0.47570202],
       [0.19375844, 0.92805278, 0.19106382, 0.162639  , 0.31076982,
        0.32159093],
       [0.91569887, 0.25901099, 0.60340414, 0.82959292, 0.88335815,
        0.7621343 ],
       [0.20118081, 0.44585832, 0.86507461, 0.0990534 , 0.46180995,
        0.12732499],
       [0.16667429, 0.79796822, 0.35466658, 0.45829151, 0.42286459,
        0.03821652]])

In [ ]:
np.random.randn(3,2)

array([[-0.00195373,  1.34499024],
       [ 0.62116559,  0.53016379],
       [-0.59855181, -0.54286963]])

In [ ]:
np.random.randint(2,4)

2

In [ ]:
np.random.randint(30,100,50)

array([49, 64, 45, 64, 46, 71, 77, 89, 78, 82, 55, 93, 43, 75, 44, 46, 89,
       95, 31, 51, 57, 40, 70, 85, 85, 75, 81, 50, 39, 40, 88, 95, 33, 99,
       62, 54, 31, 74, 71, 94, 85, 77, 74, 66, 73, 79, 55, 83, 33, 45])

In [ ]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
rand_array=np.random.randint(0,100,30)
rand_array

array([73, 95, 56, 50, 23, 20, 26, 92,  7, 69, 58, 71, 77, 20, 95, 94, 15,
       42, 31, 63, 27, 80, 37, 38, 53, 94, 92, 88, 73, 79])

In [ ]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
rand_array.min()

7

In [ ]:
rand_array.argmin()

8

In [ ]:
a=np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
a.T

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
a=np.random.rand(2,3)
a

array([[0.76133643, 0.63616114, 0.9651835 ],
       [0.62916408, 0.93450688, 0.15091792]])

In [ ]:
a.T

array([[0.76133643, 0.62916408],
       [0.63616114, 0.93450688],
       [0.9651835 , 0.15091792]])

In [ ]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
sample_array[3]

13

In [ ]:
sample_array[3:7]

array([13, 14, 15, 16])

In [ ]:
sample_array[1:4]=10
sample_array

array([10, 10, 10, 10, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [ ]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [ ]:
subset_sample_array[1:4]=1001
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [ ]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [ ]:
import numpy as np

In [ ]:
sample_matrix=np.array([[50,20,1,23],[26,7,10,45],[56,46,17,29]])
sample_matrix

array([[50, 20,  1, 23],
       [26,  7, 10, 45],
       [56, 46, 17, 29]])

In [ ]:
sample_matrix[0:2,2]

array([ 1, 10])

In [ ]:
sample_matrix[2,:]

array([56, 46, 17, 29])

In [ ]:
sample_matrix[2]

array([56, 46, 17, 29])

In [ ]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [45, 10],
       [29, 17]])

In [ ]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [ ]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [ ]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [ ]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [ ]:
np.std(sample_array)

5.477225575051661

In [ ]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [ ]:
np.max(sample_array)

19

In [ ]:
np.min(sample_array)

1

In [ ]:
np.argmax(sample_array)

18

In [ ]:
np.argmin(sample_array)

0

In [ ]:
np.var(sample_array)

30.0

In [ ]:
np.mean(sample_array)

10.0

In [ ]:
array=np.random.randn(3,4)
array

array([[ 0.0808899 , -0.03256189, -1.36955526, -0.20992317],
       [ 2.07611101,  1.84126048, -1.86222925,  1.75747245],
       [-0.73812237,  0.26993987, -0.88044337, -1.2623964 ]])

In [ ]:
np.round(array,decimals=3)

array([[ 0.081, -0.033, -1.37 , -0.21 ],
       [ 2.076,  1.841, -1.862,  1.757],
       [-0.738,  0.27 , -0.88 , -1.262]])

In [ ]:
sports=np.array(['golf','cricket','basketball','fball','ludo'])